# Generated by Django 3.2.24 on 2024-02-19 19:57

from django.db import migrations, models
import nautobot.core.dramatiq.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0103_add_db_indexes_to_object_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobresult',
            old_name='task_args',
            new_name='execution_args',
        ),
        migrations.RenameField(
            model_name='jobresult',
            old_name='celery_kwargs',
            new_name='execution_options',
        ),
        migrations.RenameField(
            model_name='jobresult',
            old_name='task_kwargs',
            new_name='execution_kwargs',
        ),
        migrations.RemoveField(
            model_name='jobresult',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='jobresult',
            name='worker',
        ),
        migrations.AlterField(
            model_name='jobresult',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=30),
        ),
    ]
